---
####################################################################################
# General System Variables
####################################################################################

# Set the hostname of the target machine
hostname: "allinone"

####################################################################################
# Docker
####################################################################################

## MicroK8s Docker socket is not in the usual place
docker_env:
  DOCKER_HOST: "unix://var/snap/microk8s/current/docker.sock"

## List of registries to be added as "insecure_registries" in /etc/docker/daemon.json
#docker_insecure_registries:
#  - registry_host:5000

####################################################################################
# Kubernetes
####################################################################################

## Type of K8s to install - defaults to Microk8s
k8s_type: microk8s

## Disable to prevent installation of Microk8s
microk8s: True

# Enable to install the K8s Dashboard
#k8s_dashboard: True

# In a multi network interface server you can specify which ip address to bind to, otherwise comment this variable out
# and the default IP address discovered by Ansible will be used
# Set this to the IP you expect to use to access open ports on the target machine.
#advertise_address: 10.220.217.248

## Disable to prevent installation of Helm
helm: True

## List of Helm repositories to add
#helm_repos:
#  - name: repo-name
#    url: repo-addr

####################################################################################
# CICDHub
####################################################################################

## Disable to prevent installation of CICDHub
cicdhub: True

## CICDHub Helm chart location
#cicdhub_helm_chart_location: https://github.com/accanto-systems/lm-cicdhub/releases/download/v2.0.5-alpha-1/cicdhub-2.0.5-alpha-1.tgz

## Additional values file to be added to the helm install command of each chart
## The file will be copied from the local machine to the target machine then included on the helm install command with the option: -f <filename>.yaml
#cicdhub_values: my-custom-values.yaml

## Enabled flags for CICDHub services
lm_nexus_enabled: True
lm_gogs_enabled: True
lm_docker_registry_enabled: True
lm_jenkins_enabled: True

####################################################################################
# Lifecycle Manager
####################################################################################

## Disable to prevent installation of LM
lm: True
## Disable to prevent installation of a Apache2 based proxy for LM
lm_proxy: True

##################################
# Lifecycle Manager - Helm Charts
##################################

lm_charts_strategy: from_package
#lm_charts_strategy: individual
## Full path to each helm chart
## If a http or https address then this role will attempt a GET to retrieve it
## If a file address then this role will attempt to copy it to the target machine from the local machine
#lm_chart: /home/accanto/lm-allinone/lm-helm-2.1.0-SNAPSHOT.tgz
#lm_foundation_chart: /home/accanto/lm-allinone/helm-foundation-2.1.0-alpha-68.tgz
#lm_configurator_chart: /home/accanto/lm-allinone/lm-configurator-2.1.0-alpha-122.tgz

lm_force_refresh_packages: True

# lm_charts_strategy: from_package
# Path to lm-helm-charts package (can be a file path or http address)
lm_charts_package: ../lm-artifacts/lm-helm-charts-<LM_VERSION>-dist.tgz

###################################
# Lifecycle Manager - Docker Images
###################################

# lm_docker_strategy: from_package
# Path to lm-docker-source package (can be file based or http)
lm_docker_package: ../lm-artifacts/lm-docker-source-<LM_VERSION>-dist.tgz

##Switch to pulling Docker Images from a registry instead
# lm_docker_strategy: from_registry
# lm_docker_registry_host: 10.220.217.113
# lm_docker_registry_port: 32736
# lm_docker_strategy: from_registry
# lm_docker_registry_host: nexus.accanto.com
# lm_docker_registry_port: 5000

###################################
# Lifecycle Manager - Configuration
###################################

# Custom values to include on the helm installation
lm_values: lm-helm-values.yml

## Disable security by removing lm_secure
lm_secure: True
# Set to change the default Admin client secret 
#lm_admin_secret: admin
# Set to change the default Openldap passwords 
#lm_ldap_manager_password: admin

## Used to theme the LM UI
#lm_theme: False
#lm_theme_directory: path to directory containing 'theme.tar' (mandatory name)
#lm_theme_name: name of theme (name of theme directory inside the theme.tar to be used)

## The following are optionally installed with LM, set to False or comment out to disable them
## By default, OpenLDAP installation is enabled for LM and disabled for OpenLDAP
lm_nginx_ingress_enabled: False
lm_filebeat_enabled: False
lm_kibana_enabled: False
lm_kafdrop_enabled: False
lm_openldap_enabled: True

####################################################################################
# Ansible RM Variables
####################################################################################

## Disable to prevent installation of Ansible RM
arm: True

##################################
# Ansible RM - Helm Chart
##################################

## Locate Ansible RM chart on a path
arm_charts_strategy: path
## Path to the Ansible RM helm chart (can be file based or http)
arm_chart: https://github.com/IBM/osslm-ansible-resource-manager/releases/download/v1.3.4/osslm-ansible-resource-manager-1.3.4.tgz

##################################
# Ansible RM - Docker Images
##################################

## Pull the Docker Image from DockerHub (or a registry by including registry info on arm_docker_image e.g. host:port/osslm-ansible-rm)
arm_docker_strategy: from_image
arm_docker_image: accanto/osslm-ansible-rm
arm_docker_version: 1.3.4

## Disable https by removing arm_secure
arm_secure: True

####################################################################################
# Portainer
####################################################################################

## Enable to include installation of Portainer
portainer: False
