---
####################################################################################
# General System Variables
####################################################################################

# Set the hostname of the target machine
hostname: "allinone"

####################################################################################
# Docker
####################################################################################

## Disable to prevent installation of Docker
docker: True

## List of registries to be added as "insecure_registries" in /etc/docker/daemon.json
#docker_insecure_registries:
#  - registry_host:5000

####################################################################################
# Kubernetes
####################################################################################

## Disable to prevent installation of Kubeadm
kubeadm: True

# Enable to install the K8s Dashboard with Kubeadm
#kube_dashboard: True

# In a multi network interface server you can specify which ip address to bind kubeadm to, otherwise comment this variable out
# and the default IP address discovered by Ansible will be used
# Set this to the IP you expect to use to access open ports on the target machine.
kubeadm_advertise_address: 192.168.56.100

# With a vagrant environment the first network interface is used by Vagrant. The network interface to bind kubeadm to must be specified here, e.g. eth1.
# If provisioning a non-vagrant AIO environment change this variable to the main network interface or comment out and Ansible will use the default interface name.
# If you have set `kubeadm_advertise_address` then the recommended way determine the correct flannel_interface is to
# run `ifconfig` on the target machine, find the entry with the address you used on `kubeadm_advertise_address`, enter the name of that entry here.
flannel_interface: "eth1"

## Disable to prevent installation of Helm
helm: True

## List of Helm repositories to add
#helm_repos:
#  - name: repo-name
#    url: repo-addr

####################################################################################
# Lifecycle Manager
####################################################################################

## Disable to prevent installation of LM
lm: True
## Disable to prevent installation of a Apache2 based proxy for LM
lm_proxy: True

##################################
# Lifecycle Manager - Helm Charts
##################################

lm_charts_strategy: from_package
# Path to lm-helm-charts package (can be a file path or http address)
lm_charts_package: ../lm-artifacts/lm-helm-charts-<LM_VERSION>-dist.tgz

###################################
# Lifecycle Manager - Docker Images
###################################

lm_docker_strategy: from_package
# Path to lm-docker-source package (can be file based or http)
lm_docker_package: ../lm-artifacts/lm-docker-source-<LM_VERSION>-dist.tgz

##Switch to pulling Docker Images from a registry instead
#lm_docker_strategy: from_registry
#lm_docker_registry_host: registry_host
#lm_docker_registry_port: 5000

###################################
# Lifecycle Manager - Configuration
###################################

# Custom values to include on the helm installation
lm_values: lm-helm-values.yml

## Run helper script to create directories for persistent volumes (required when using local volumes, which is the default)
lm_init_volumes: True

## Disable security by removing lm_secure
lm_secure: True
# Set to change the default Admin client secret 
#lm_admin_secret: admin
# Set to change the default Openldap passwords 
#lm_ldap_manager_password: admin

## Used to theme the LM UI
#lm_theme: False
#lm_theme_directory: path to directory containing 'theme.tar' (mandatory name)
#lm_theme_name: name of theme (name of theme directory inside the theme.tar to be used)

## The following are optionally installed with LM, set to False or comment out to disable them
lm_kibana_enabled: True
#lm_kafdrop_enabled: True

####################################################################################
# Ansible RM Variables
####################################################################################

## Disable to prevent installation of Ansible RM
arm: True

##################################
# Ansible RM - Helm Chart
##################################

## Locate Ansible RM chart on a path
arm_charts_strategy: path
## Path to the Ansible RM helm chart (can be file based or http)
arm_chart: https://github.com/IBM/osslm-ansible-resource-manager/releases/download/v1.3.4/osslm-ansible-resource-manager-1.3.4.tgz

##################################
# Ansible RM - Docker Images
##################################

## Pull the Docker Image from DockerHub (or a registry by including registry info on arm_docker_image e.g. host:port/osslm-ansible-rm)
arm_docker_strategy: from_image
arm_docker_image: accanto/osslm-ansible-rm
arm_docker_version: 1.3.4

## Disable https by removing arm_secure
arm_secure: True
####################################################################################
# Portainer
####################################################################################

## Enable to include installation of Portainer
portainer: False
