- src: https://github.com/accanto-systems/ansible-role-lifecyclemanager-proxy.git
  scm: git
  name: lifecyclemanager-proxy

- src: https://github.com/accanto-systems/ansible-role-lifecyclemanager.git
  scm: git
  name: lifecyclemanager

- src: https://github.com/accanto-systems/ansible-role-docker.git
  scm: git
  name: docker

- src: https://github.com/accanto-systems/ansible-role-kubeadm.git
  scm: git
  name: kubeadm

- src: https://github.com/accanto-systems/ansible-role-helm.git
  scm: git
  name: helm

- src: https://github.com/accanto-systems/ansible-role-ansiblerm.git
  scm: git
  name: ansiblerm
