---
- hosts: all
  become: true
  gather_facts: no
  become_method: sudo
  vars_files:
    - ansible-variables.yml
  tasks:
    - import_role:
        name: initial-setup

    - import_role:
        name: docker
      when: docker|default(False)|bool == True

    - import_role:
        name: kubeadm
      when: kubeadm|default(False)|bool == True

    - import_role:
        name: helm
      when: helm|default(False)|bool == True

    - import_role:
        name: lifecyclemanager
      when: lm|default(False)|bool == True

    - import_role:
        name: lifecyclemanager-proxy
      when: lm|default(False)|bool == True and lm_proxy|default(False)|bool == True

    - import_role:
        name: ansiblerm
      vars:
        arm_onboard_addr: "{{ lm_proxy_api_addr }}" #set by lifecyclemanager-proxy role
        arm_onboard_auth: "{{ (lm_secure|default(False)|bool) == True }}"
        arm_docker_location_lm_ip: "{{ kubeadm_advertise_address if kubeadm_advertise_address is defined else hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        arm_docker_location_relay_addr: "{{ kubeadm_advertise_address if kubeadm_advertise_address is defined else hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:31285"
        arm_onboard_client_secret: "{{ lm_admin_secret|default('') }}"
      when: arm|default(False)|bool == True

    - import_role:
        name: portainer
      when: portainer|default(False)|bool == True

    - import_role:
        name: tutorials
      when: tutorials|default(False)|bool == True
