---
- hosts: all
  become: true
  gather_facts: no
  become_method: sudo
  vars_files:
    - ansible-variables.yml
  tasks:
    - import_role:
        name: initial-setup

    - import_role:
        name: microk8s
      when: k8s_type|default('microk8s')|string == 'microk8s' and microk8s|default(False)|bool == True

    - import_role:
        name: helm
      when: helm|default(False)|bool == True

    - import_role:
        name: cicdhub
      when: cicdhub|default(False)|bool == True

    - import_role:
        name: lifecyclemanager
      when: lm|default(False)|bool == True

    # MicroK8s ingress runs on ports 80 and 443, so use different ports. MicroK8s API server
    # runs on port 8080, so use different ports for proxy ports.
    - name: Set Proxy Ports
      set_fact:
        lm_ui_non_ssl_port: 80
        lm_ui_ssl_port: 443
        lm_api_non_ssl_port: 80
        lm_api_ssl_port: 443
        lm_ui_proxy_port: 8082
        lm_api_proxy_port: 8083

    - import_role:
        name: lifecyclemanager-proxy
      when: lm|default(False)|bool == True and lm_proxy|default(False)|bool == True

    - import_role:
        name: ansiblerm
      vars:
        arm_onboard_addr: "{{ lm_proxy_api_addr }}" #set by lifecyclemanager-proxy role
        arm_onboard_auth: "{{ (lm_secure|default(False)|bool) == True }}"
        arm_docker_location_lm_ip: "{{ advertise_address if advertise_address is defined else hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        arm_docker_location_relay_addr: "{{ advertise_address if advertise_address is defined else hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:31285"
        arm_onboard_client_secret: "{{ lm_admin_secret|default('') }}"
      when: arm|default(False)|bool == True

    - import_role:
        name: portainer
      when: portainer|default(False)|bool == True

    - import_role:
        name: tutorials
      when: tutorials|default(False)|bool == True
